site_name: LAMPrEY Documentation
nav:
    - Home: index.md
    - Getting Started:
        - Overview: getting-started.md
        - Installation: installation.md
        - Demo data: demo.md
    - Application:
        - Overview: application.md
        - Admin panel:
            - Overview: how-to-access-the-admin-panel.md
            - Add a user: how-to-add-a-user.md
            - Create a project: how-to-add-a-project.md
            - Prepare mqpar.xml: how-to-prepare-mqpar.md
            - Create a pipeline: how-to-add-a-pipeline.md
            - Submit RAW files: how-to-submit-raw-files.md
            - Run picked-group FDR: how-to-run-picked-group-fdr.md
        - Main: main.md
        - Dashboard: dashboard.md
    - System:
        - Datalake: datalake.md
        - RawTools: rawtools.md
        - MaxQuant: maxquant.md
    - Resources:
        - API: api.md
        - About: about.md
        - Help/Issues: issues.md
extra:
  analytics:
      provider: google
      property: G-3B0G926SJ2   
repo_name: LAMPrEY
repo_url: https://github.com/LewisResearchGroup/LAMPrEY
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
  - stylesheets/termy.css
extra_javascript:
  - javascripts/termy.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js
plugins:
  - search
  - glightbox
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
