# Generated by Django 5.2.12 on 2026-04-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maxquant", "0024_alter_rawtoolssetup_rawtools_args"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_last_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_last_manifest",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_last_run_dir",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_last_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_last_status",
            field=models.CharField(default="never_run", max_length=32),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="picked_group_fdr_task_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
