#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
DATA_DIR="$PROJECT_ROOT/data"

echo '# LAMPrEY CONFIG' > "$ENV_FILE"

echo """
## HOMEPAGE SETTINGS
HOME_TITLE='LAMPrEY'
HOSTNAME=localhost
ALLOWED_HOSTS=localhost
CSRF_TRUSTED_ORIGINS=http://localhost
OMICS_URL=http://localhost:8000
""" >> "$ENV_FILE"

echo """## STORAGE
DATALAKE=./data/datalake
COMPUTE=./data/compute
MEDIA=./data/media
STATIC=./data/static
DB=./data/db
""" >> "$ENV_FILE"

echo """## EMAIL SETTINGS
EMAIL_HOST=smtp.gmail.com
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False
EMAIL_PORT=587
EMAIL_HOST_USER=''
EMAIL_HOST_PASSWORD=''
DEFAULT_FROM_EMAIL=''
""" >> "$ENV_FILE"

echo """## CELERY
CONCURRENCY=8
RESOURCE_RETRY_SECONDS=60
MIN_FREE_MEM_GB_MAXQUANT=8
MAX_LOAD_PER_CPU_MAXQUANT=0.85
MIN_FREE_MEM_GB_RAWTOOLS=2
MAX_LOAD_PER_CPU_RAWTOOLS=0.90

## RESULT STATUS (web UI responsiveness vs strictness)
RESULT_STATUS_INSPECT_TIMEOUT_SECONDS=10.0
RESULT_STATUS_PENDING_STALLED_WARNING_SECONDS=7200
RESULT_STATUS_DONE_MTIME_SKEW_SECONDS=300
RESULT_STATUS_MAXQUANT_STALE_SECONDS=21600
RESULT_STATUS_RAWTOOLS_STALE_SECONDS=3600
RESULT_STATUS_ACTIVITY_FALLBACK_SECONDS=300
RESULT_STATUS_CANCEL_ACTIVITY_SECONDS=20
RESULT_STATUS_INSPECT_MAX_VISIBLE_RUNS=25
RESULT_STATUS_INSPECT_MAX_ACTIVE_RUNS=12
""" >> "$ENV_FILE"

echo """##USERID
UID=$(id -u):$(id -g)
""">> "$ENV_FILE"

echo "## SECURITY KEYS" >> "$ENV_FILE"
echo "SECRET_KEY=$( openssl rand -hex 32 )" >> "$ENV_FILE"

# keep generated data writable by the host user, even if the script is run via sudo
OWNER_UID="${SUDO_UID:-$(id -u)}"
OWNER_GID="${SUDO_GID:-$(id -g)}"

# this prevents permission issues
mkdir -p "$DATA_DIR"/{compute,datalake,db,media,static}
chown -R "$OWNER_UID":"$OWNER_GID" "$DATA_DIR"
